CREATE TABLE PUB_PERMISSION 
(
  ID VARCHAR2(32 CHAR) NOT NULL ,
  NAME VARCHAR2(50 CHAR) NULL ,
  CODE VARCHAR2(255 CHAR) NULL ,
  MENU_ID VARCHAR2(32 CHAR) NULL ,
  REMARK VARCHAR2(255 CHAR) NULL 
);