
-- 短信通道表

CREATE TABLE PUB_MENU 
(
  ID VARCHAR2(32 CHAR) NOT NULL ,
  HAS_CHILD CHAR(1 BYTE) NULL ,
  ICON VARCHAR2(20 CHAR) NULL ,
  NODE VARCHAR2(1 CHAR) NULL ,
  PARENT_ID VARCHAR2(32 CHAR) NULL ,
  PATH VARCHAR2(100 CHAR) NULL ,
  SORT NUMBER(10) NULL ,
  TITLE VARCHAR2(30 CHAR) NULL ,
  IS_SHOW VARCHAR2(1 CHAR) NULL ,
  REMARK VARCHAR2(255 CHAR) NULL 
);