CREATE TABLE PUB_ROLE 
(
ID VARCHAR2(32 CHAR) NOT NULL ,
NAME VARCHAR2(30 CHAR) NULL ,
CREATE_BY VARCHAR2(30 CHAR) NULL ,
CREATE_TIME TIMESTAMP(6)  NULL ,
IS_TMP CHAR(1 BYTE) NULL ,
REMARK VARCHAR2(255 CHAR) NULL 
);