ALTER TABLE PUB_ROLE_PERMISSION ADD UNIQUE (ROLE_ID, PERMISSION_ID);
ALTER TABLE PUB_ROLE_PERMISSION ADD CHECK (ROLE_ID IS NOT NULL);
ALTER TABLE PUB_ROLE_PERMISSION ADD CHECK (PERMISSION_ID IS NOT NULL);