CREATE TABLE PUB_USER 
(
  ID VARCHAR2(32 CHAR) NOT NULL ,
  USERNAME VARCHAR2(30 CHAR) NULL ,
  PASSWORD VARCHAR2(80 CHAR) NULL ,
  PAY_PASSWD VARCHAR2(50 CHAR) NULL ,
  STATUS VARCHAR2(5 CHAR) NULL ,
  FAIL_COUNT NUMBER(10) NULL ,
  LOCKED_TIME TIMESTAMP(6)  NULL ,
  CREATE_BY VARCHAR2(30 CHAR) NULL ,
  CREATE_TIME TIMESTAMP(6)  NULL ,
  REMARK VARCHAR2(255 CHAR) NULL ,
  SALT VARCHAR2(32 CHAR) NULL 
);