CREATE TABLE PUB_PARAM 
(
  CODE VARCHAR2(20 CHAR) NOT NULL ,
  NAME VARCHAR2(50 CHAR) NULL ,
  GROUP_CODE VARCHAR2(20 CHAR) NULL ,
  DECIMAL_VAL NUMBER(18,6) NULL ,
  INT_VAL NUMBER(10) NULL ,
  STR_VAL VARCHAR2(255 CHAR) NULL ,
  BOOLEAN_VAL VARCHAR2(10 CHAR) NULL ,
  TYPE VARCHAR2(2 CHAR) NULL ,
  MODIFY_FLAG VARCHAR2(1 CHAR) NULL ,
  REMARK VARCHAR2(255 CHAR) NULL 
);