CREATE TABLE PUB_LOGIN_LOG 
(
  ID VARCHAR2(32 CHAR) NOT NULL ,
  USERNAME VARCHAR2(30 CHAR) NULL ,
  AGENT VARCHAR2(255 CHAR) NULL ,
  IP VARCHAR2(40 CHAR) NULL ,
  LOGIN_DATE TIMESTAMP(6)  NULL ,
  STATUS VARCHAR2(2 CHAR) NULL ,
  REMARK VARCHAR2(255 CHAR) NULL 
);