CREATE TABLE PUB_OPERATION_LOG 
(
  ID VARCHAR2(32 CHAR) NOT NULL ,
  USERNAME VARCHAR2(30 CHAR) NULL ,
  MENU_ID VARCHAR2(32 CHAR) NULL ,
  PERMISSION_ID VARCHAR2(32 CHAR) NULL ,
  CONTROLLER VARCHAR2(200 CHAR) NULL ,
  METHOD VARCHAR2(200 CHAR) NULL ,
  IP VARCHAR2(40 CHAR) NULL ,
  CREATE_TIME TIMESTAMP(6)  NULL ,
  ELAPSED_TIME NUMBER(10) NULL ,
  STATUS VARCHAR2(2 CHAR) NULL ,
  REMARK CLOB NULL 
);