CREATE TABLE PUB_MSG_CHANNEL_APP 
(
  ID VARCHAR2(32 CHAR) NOT NULL ,
  CODE VARCHAR2(4 CHAR) NOT NULL ,
  APP_NAME VARCHAR2(50 CHAR) NOT NULL ,
  CHANNEL_CODE VARCHAR2(2 CHAR) NOT NULL ,
  ACCESS_KEY_ID VARCHAR2(100 CHAR) NOT NULL ,
  ACCESS_KEY_SECRET VARCHAR2(200 CHAR) NOT NULL ,
  CREATE_TIME TIMESTAMP(6)  NOT NULL ,
  CREATE_BY VARCHAR2(30 CHAR) NOT NULL ,
  REMARK VARCHAR2(255 CHAR) NULL ,
  NOTIFY_URL VARCHAR2(500 BYTE) NULL 
);