CREATE TABLE PUB_MSG_VER_CODE_SIGN 
(
  ID VARCHAR2(32 CHAR) NOT NULL ,
  VER_CODE VARCHAR2(32 CHAR) NOT NULL ,
  SIGN_CODE VARCHAR2(6 CHAR) NOT NULL ,
  CHANNEL_CODE VARCHAR2(2 CHAR) NOT NULL ,
  APP_CODE VARCHAR2(4 CHAR) NOT NULL ,
  CREATE_TIME TIMESTAMP(6)  NOT NULL ,
  CREATE_BY VARCHAR2(30 CHAR) NOT NULL ,
  REMARK VARCHAR2(255 CHAR) NULL 
);
COMMENT ON COLUMN PUB_MSG_VER_CODE_SIGN.ID IS 'UUID';
COMMENT ON COLUMN PUB_MSG_VER_CODE_SIGN.VER_CODE IS '手机验证业务编号';
COMMENT ON COLUMN PUB_MSG_VER_CODE_SIGN.SIGN_CODE IS '平台签名编号';
COMMENT ON COLUMN PUB_MSG_VER_CODE_SIGN.CHANNEL_CODE IS '通道编号';
COMMENT ON COLUMN PUB_MSG_VER_CODE_SIGN.APP_CODE IS '应用名称';
COMMENT ON COLUMN PUB_MSG_VER_CODE_SIGN.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN PUB_MSG_VER_CODE_SIGN.CREATE_BY IS '创建人';
COMMENT ON COLUMN PUB_MSG_VER_CODE_SIGN.REMARK IS '备注';