CREATE TABLE PUB_MSG_CHANNEL_TEMPLATE 
(
  ID VARCHAR2(32 CHAR) NOT NULL ,
  CODE VARCHAR2(6 CHAR) NOT NULL ,
  NAME VARCHAR2(32 CHAR) NOT NULL ,
  CHANNEL_TEMPLATE_CODE VARCHAR2(32 CHAR) NULL ,
  CHANNEL_TEMPLATE_NAME VARCHAR2(64 CHAR) NULL ,
  PARAM VARCHAR2(200 CHAR) NULL ,
  CONTENT VARCHAR2(200 CHAR) NOT NULL ,
  CHANNEL_CODE VARCHAR2(2 CHAR) NOT NULL ,
  APP_CODE VARCHAR2(4 CHAR) NOT NULL ,
  STATUS VARCHAR2(2 CHAR) NOT NULL ,
  CREATE_TIME TIMESTAMP(6)  NOT NULL ,
  CREATE_BY VARCHAR2(30 CHAR) NOT NULL ,
  REMARK VARCHAR2(255 CHAR) NULL,
  CHANNEL_CONTENT VARCHAR2(200) NULL
);