CREATE TABLE PUB_MSG_VER_CODE_TEMPLATE 
(
  ID VARCHAR2(32 CHAR) NOT NULL ,
  VER_CODE VARCHAR2(3 CHAR) NOT NULL ,
  TEMPLATE_CODE VARCHAR2(6 CHAR) NOT NULL ,
  CHANNEL_CODE VARCHAR2(2 CHAR) NOT NULL ,
  APP_CODE VARCHAR2(4 CHAR) NOT NULL ,
  CREATE_TIME TIMESTAMP(6)  NOT NULL ,
  CREATE_BY VARCHAR2(30 CHAR) NOT NULL ,
  REMARK VARCHAR2(255 CHAR) NULL 
);
COMMENT ON COLUMN PUB_MSG_VER_CODE_TEMPLATE.ID IS 'UUID';
COMMENT ON COLUMN PUB_MSG_VER_CODE_TEMPLATE.VER_CODE IS '手机验证业务编号';
COMMENT ON COLUMN PUB_MSG_VER_CODE_TEMPLATE.TEMPLATE_CODE IS '模板编号';
COMMENT ON COLUMN PUB_MSG_VER_CODE_TEMPLATE.CHANNEL_CODE IS '通道编号';
COMMENT ON COLUMN PUB_MSG_VER_CODE_TEMPLATE.APP_CODE IS '应用编号';
COMMENT ON COLUMN PUB_MSG_VER_CODE_TEMPLATE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN PUB_MSG_VER_CODE_TEMPLATE.CREATE_BY IS '创建人';
COMMENT ON COLUMN PUB_MSG_VER_CODE_TEMPLATE.REMARK IS '备注';