ALTER TABLE PUB_MSG_VER_CODE_TEMPLATE ADD UNIQUE (VER_CODE, TEMPLATE_CODE, CHANNEL_CODE, APP_CODE);
ALTER TABLE PUB_MSG_VER_CODE_TEMPLATE ADD CHECK (ID IS NOT NULL);
ALTER TABLE PUB_MSG_VER_CODE_TEMPLATE ADD CHECK (VER_CODE IS NOT NULL);
ALTER TABLE PUB_MSG_VER_CODE_TEMPLATE ADD CHECK (TEMPLATE_CODE IS NOT NULL);
ALTER TABLE PUB_MSG_VER_CODE_TEMPLATE ADD CHECK (CHANNEL_CODE IS NOT NULL);
ALTER TABLE PUB_MSG_VER_CODE_TEMPLATE ADD CHECK (APP_CODE IS NOT NULL);
ALTER TABLE PUB_MSG_VER_CODE_TEMPLATE ADD CHECK (CREATE_TIME IS NOT NULL);
ALTER TABLE PUB_MSG_VER_CODE_TEMPLATE ADD CHECK (CREATE_BY IS NOT NULL);
ALTER TABLE PUB_MSG_VER_CODE_TEMPLATE ADD PRIMARY KEY (ID);
