CREATE INDEX CREATE_TIME_INDEX
ON PUB_SMS_RECORD (CREATE_TIME ASC)
LOGGING
VISIBLE;
CREATE INDEX PHONE_INDEX
ON PUB_SMS_RECORD (PHONE ASC)
LOGGING
VISIBLE;
ALTER TABLE PUB_SMS_RECORD ADD CHECK (ID IS NOT NULL);
ALTER TABLE PUB_SMS_RECORD ADD CHECK (PHONE IS NOT NULL);
ALTER TABLE PUB_SMS_RECORD ADD CHECK (CREATE_TIME IS NOT NULL);
ALTER TABLE PUB_SMS_RECORD ADD CHECK (CONTENT IS NOT NULL);
ALTER TABLE PUB_SMS_RECORD ADD CHECK (TYPE IS NOT NULL);
ALTER TABLE PUB_SMS_RECORD ADD PRIMARY KEY (ID);
