CREATE TABLE PUB_SMS_RECORD 
(
  ID VARCHAR2(32 CHAR) NOT NULL ,
  PHONE VARCHAR2(20 CHAR) NOT NULL ,
  CREATE_TIME TIMESTAMP(6)  NOT NULL ,
  CONTENT VARCHAR2(255 CHAR) NOT NULL ,
  TYPE VARCHAR2(2 CHAR) NOT NULL ,
  REMARK VARCHAR2(255 CHAR) NULL ,
  STATUS VARCHAR2(2 CHAR) NULL ,
  CHANNEL_CODE VARCHAR2(2 BYTE) NULL ,
  CHANNEL_MSG_ID VARCHAR2(32 BYTE) NULL ,
  USER_RECEIVE_TIME TIMESTAMP(6)  NULL ,
  APP_CODE VARCHAR2(4 BYTE) NULL ,
  NOTIFY_RESULT CHAR(1 BYTE) NULL ,
  NOTIFY_TIMES NUMBER(3) NULL ,
  MID VARCHAR2(15 BYTE) NULL ,
  VER_CODE VARCHAR2(3 BYTE) NULL ,
  SIGN_CODE VARCHAR2(6 BYTE) NULL ,
  SIGN_NAME VARCHAR2(32 BYTE) NULL ,
  CHANNEL_SIGN_NAME VARCHAR2(64 BYTE) NULL 
);